name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.platform }}

    steps:
    # - name: Install missing packages
    #   run: sudo apt install xsel
    #   if: matrix.platform == 'ubuntu-latest'

    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
